set_property PACKAGE_PIN N18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN F19 [get_ports TMDS_CLK_p]
set_property PACKAGE_PIN D19 [get_ports {TMDS_DATA_p[0]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS_DATA_p[1]}]
set_property PACKAGE_PIN B19 [get_ports {TMDS_DATA_p[2]}]

set_property IOSTANDARD TMDS_33 [get_ports TMDS_CLK_p]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_DATA_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_DATA_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_DATA_p[2]}]
